### ISSUE TITLE
Flow's 'Object' should be mapped to TypeScript's 'object'

### ISSUE THREAD

**Issue by diskshima** [Kiikurage/babel-plugin-flow-to-typescript#20]
Currently Flow's `Object` gets mapped to `Object` in TypeScript which results in an error in TypeScript.

I think this is because the parser treats it as a `GenericTypeAnnotation` (See `obj1` in [this example](https://astexplorer.net/#/gist/c954d94e7c6abcd249d896c83713f982/0c48e6e9a86bf66187b671a5979148be27c1d0c0)).

I believe most people are using `Object` to mean `object` in TypeScript so the implementation should map nodes with `GenericTypeAnnotation` named `Object` to `tSObjectKeyword` (i.e. `object`).

**Comment by satya164** [comment]
Maybe it should be `object`?

**Comment by diskshima** [comment]
@satya164 Yeah, you're right. Probably won't see primitives being used so `object` should be the way to go.
I've changed the title and body.
