### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jack-guy** [Kiikurage/babel-plugin-flow-to-typescript#31]
Very interested in using this plugin, but I want to make sure I have permission to do so. Is this plugin MIT-licensed?

**Comment by Kiikurage** [comment]
Sorry for too much late reply. I'll update soon!!!

**Comment by Kiikurage** [comment]
Updated

**Comment by jack-guy** [comment]
Thanks so much @Kiikurage! So excited to start migrating some flow code!
