### ISSUE TITLE
Latest of master is still unpublished

### ISSUE THREAD

**Issue by chrisdopuch** [Kiikurage/babel-plugin-flow-to-typescript#37]
Hello!

I love this library, I'm using it right now to migrate a bunch of Flow code to TS! ❤️ 

However, I'm hitting this bug https://github.com/Kiikurage/babel-plugin-flow-to-typescript/issues/36, which is fixed on master but not yet published.

Could we pretty please get the latest version published? 🙏 

Thanks for making this awesome plugin!

**Comment by TomPridham** [comment]
@chrisdopuch, im not sure if you're still blocked on this, but you can install from directly from the repo like `npm i -D babel-plugin-flow-to-typescript@git@github.com:Kiikurage/babel-plugin-flow-to-typescript.git`

**Comment by Kiikurage** [comment]
Sorry for too late notice. I published `0.6.0` just now.
