### ISSUE TITLE
Active Development?

### ISSUE THREAD

**Issue by rouzbeh84** [Kiikurage/babel-plugin-flow-to-typescript#7]
Is this being maintained? I just ran it on a file using flow/react and it failed on seeing a `className` and after just removing it to see if it would continue, it fails on another jsx block. 

![image](https://user-images.githubusercontent.com/1803843/41995624-51e08604-7a07-11e8-8099-2bfec065b185.png)

would be great if this worked 👍 also I could be doing it wrong as it's on a `js` file?

**Comment by teramotodaiki** [comment]
I think it needs more babel plugins to parse JSX/Flow syntax.

e.g.

```.babelrc
{
  "plugins": [
    "@babel/plugin-syntax-jsx",
    "@babel/plugin-syntax-flow"
    "babel-plugin-flow-to-typescript"
  ]
}
```

Or you should add other syntax plugins if needed.
If you use react-create-app,

```.babelrc
{
  "plugins": [
    "@babel/plugin-syntax-jsx",
    "@babel/plugin-syntax-flow",
    "@babel/plugin-syntax-object-rest-spread",
    "@babel/plugin-syntax-class-properties",
    "@babel/plugin-syntax-dynamic-import",
    "babel-plugin-flow-to-typescript"
  ]
}
```

**Comment by diskshima** [comment]
Yes this plugin isn't loading in the plugin to parse JSX (only loads the one for flow).
I've created a pull request (#13) to address this.

**Comment by Kiikurage** [comment]
Sorry, I didn't notice many PRs are coming. I'll check them soon!

**Comment by Kiikurage** [comment]
Thanks to #13, this problem should be resolved. Thank you @diskshima!
